import Styles from "./alphabet.module.css";

function Alphabet({ fontFamily, fontType }) {
  return (
    <div className={Styles.alphabet}>
      {fontType === "unicode" && (
        <div className={Styles.table}>
          <table style={{ fontFamily: `${fontFamily}` }}>
            <tr>
              <td>w</td>
              <td>wd</td>
              <td>we</td>
              <td>wE</td>
              <td>b</td>
              <td>B</td>
            </tr>
            <tr>
              <td>W</td>
              <td>W!</td>
              <td>R</td>
              <td>t</td>
              <td>ta</td>
              <td>ft</td>
            </tr>
            <tr>
              <td>T</td>
              <td>´</td>
              <td>T!</td>
              <td>wx</td>
              <td>w#</td>
              <td></td>
            </tr>
            <tr>
              <td>l</td>
              <td>L</td>
              <td>.</td>
              <td>-</td>
              <td>-</td>
              <td>Õ</td>
            </tr>
            <tr>
              <td>p</td>
              <td>P</td>
              <td>c</td>
              <td>CO</td>
              <td>-</td>
              <td>-</td>
            </tr>
            <tr>
              <td>g</td>
              <td>G</td>
              <td>v</td>
              <td>V</td>
              <td>K</td>
              <td>-</td>
            </tr>
            <tr>
              <td>;</td>
              <td>:</td>
              <td>o</td>
              <td>O</td>
              <td>k</td>
              <td>|</td>
            </tr>
            <tr>
              <td>m</td>
              <td>M</td>
              <td>n</td>
              <td>N</td>
              <td>u</td>
              <td>U</td>
            </tr>
            <tr>
              <td>h</td>
              <td>r</td>
              <td>,</td>
              <td>j</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>Y</td>
              <td>I</td>
              <td>i</td>
              <td>y</td>
              <td>-</td>
              <td>*</td>
            </tr>
          </table>
        </div>
      )}

      {fontType === "legacy" && (
        <div className={Styles.table}>
          <table style={{ fontFamily: `${fontFamily}` }}>
            <tr>
              <td>අ</td>
              <td>ආ</td>
              <td>ඇ</td>
              <td>ඈ</td>
              <td>ඉ</td>
              <td>ඊ</td>
            </tr>
            <tr>
              <td>උ</td>
              <td>ඌ</td>
              <td>ඍ</td>
              <td>එ</td>
              <td>ඒ</td>
              <td>ඓ</td>
            </tr>
            <tr>
              <td>ඔ</td>
              <td>ඕ</td>
              <td>ඖ</td>
              <td>අං</td>
              <td>අඃ</td>
              <td></td>
            </tr>
            <tr>
              <td>ක</td>
              <td>ඛ</td>
              <td>ග</td>
              <td>-</td>
              <td>-</td>
              <td>ඟ</td>
            </tr>
            <tr>
              <td>ච</td>
              <td>ඡ</td>
              <td>ජ</td>
              <td>ඣ</td>
              <td>-</td>
              <td>-</td>
            </tr>
            <tr>
              <td>ට</td>
              <td>ඨ</td>
              <td>ඩ</td>
              <td>ඪ</td>
              <td>ණ</td>
              <td>-</td>
            </tr>
            <tr>
              <td>ත</td>
              <td>ථ</td>
              <td>ද</td>
              <td>ධ</td>
              <td>න</td>
              <td>ඳ</td>
            </tr>
            <tr>
              <td>ප</td>
              <td>ඵ</td>
              <td>බ</td>
              <td>භ</td>
              <td>ම</td>
              <td>ඹ</td>
            </tr>
            <tr>
              <td>ය</td>
              <td>ර</td>
              <td>ල</td>
              <td>ව</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>ශ</td>
              <td>ෂ</td>
              <td>ස</td>
              <td>හ</td>
              <td>-</td>
              <td>ෆ</td>
            </tr>
          </table>
        </div>
      )}
    </div>
  );
}

export default Alphabet;
